### ISSUE TITLE
Consider providing a `FlushWait()` API

### ISSUE THREAD

**Issue by evantorrie** [gammazero/workerpool#20]
Just as we have a `StopWait()` api that will wait until all tasks in the queue are 
a.  submitted to the worker goroutines
b.  wait until all of the existing + newly submitted goroutines have run to completion
and then shuts down the worker pool, I wonder if we others have requested a 

`Flush|FlushWait()` API that does the same as `Stop|StopWait()` but doesn't shut down the workergroup, instead allowing the worker goroutines to continue to run and keep processing any tasks submitted after the calll to `Flush|FlushWait()`.

The idea being that it may be useful to ensure that all currently executing tasks and queued tasks in a workerpool have completed, to ensure a known "sync" state, but then continue to run normally after that.

**Comment by gammazero** [comment]
You are the first to request this feature. Typically that has been solved by using a `sync.Waitgroup` in the tasks and then waiting for a group of tasks to all complete. I think solving the problem that way offers more flexibility as tasks can be part of any group, depending on the `sync.Waitgroup` they use. A `FlushWait` API would only allow for one group, which is all the current tasks.

Your suggestion certainly offers value, however I would prefer to omit that feature (at least for now) in favor of clients using wait groups or similar.  Thank you for this.  I will give it a bit more thought.

**Comment by gammazero** [comment]
Closing issue as per above: https://github.com/gammazero/workerpool/issues/20#issuecomment-538675491
