### ISSUE TITLE
What the best way for pause pool?

### ISSUE THREAD

**Issue by DeadNumbers** [gammazero/workerpool#26]
something like this
```Go
package main

import (
	"fmt"
	"github.com/gammazero/workerpool"
	"time"
)

var isPaused = 1

func main() {
	go func() {
		time.Sleep(time.Second * 10)
		isPaused = 0
	}()
	wp := workerpool.New(2)
	requests := []string{"alpha", "beta", "gamma", "delta", "epsilon"}

	for _, r := range requests {
		r := r
		wp.Submit(func() {
			pause()
			fmt.Println("Handling request:", r)
		})
	}

	wp.StopWait()
}

func pause() int {
	if isPaused == 1 {
		time.Sleep(time.Millisecond * 100)
		return pause()
	} else {
		return 0
	}
}
```

**Comment by gammazero** [comment]
If the purpose of the pause is to make sure that there is some delay between execution of tasks, or that tasks are not executed faster than N per time, then you can use [pacer](https://github.com/gammazero/workerpool/tree/master/pacer) for this.  See [godoc](https://godoc.org/github.com/gammazero/workerpool/pacer) for examples.

If you need workerpool to actually pause execution, while continuing to queue submitted tasks, this will not be done by workerpool itself as that would complicate the dispatcher loop, and it can be done by your tasks:  Submit a number of tasks, where the number is the same as the workerpool size.  Each task signals a waitgroup to say that it is running, and then it waits on a channel to be released.  Your application can then wait on the waitgroup for all tasks to be executing (waiting).  This causes all workers waiting while workerpool continues to queue new tasks.  When you are ready to unpause, close the channel that all the tasks are waiting on.

**Comment by gammazero** [comment]
Here is an implementation of pause as described in the 2nd paragraph above:
```go
package main

import (
	"context"
	"fmt"
	"sync"

	"github.com/gammazero/workerpool"
)

func pause(ctx context.Context, wp *workerpool.WorkerPool) {
	ready := new(sync.WaitGroup)
	ready.Add(wp.Size())
	for i := 0; i < wp.Size(); i++ {
		wp.Submit(func() {
			ready.Done()
			<-ctx.Done()
		})
	}
	// Wait for workers to all be paused
	ready.Wait()
}

func main() {
	wp := workerpool.New(2)

	ctx, cancel := context.WithCancel(context.Background())

	wp.Submit(func() {
		fmt.Println("running task before pause")
	})

	fmt.Println("===> pausing")
	pause(ctx, wp)

	for i := 1; i < 4; i++ {
		wp.Submit(func() {
			fmt.Println("running task after pause")
		})
	}

	// Cancel the context to unpause the workers.
	fmt.Println("===> unpausing")
	cancel()

	wp.StopWait()
	fmt.Println("===> done")
}
```

While this could be build into workerpool, I would prefer it not be, as it is it not a common use case and can be done externally as in this example.

**Comment by gammazero** [comment]
After further consideration, I have decided to include the above pause functionality into the code.  There is now a [`Pause`](https://godoc.org/github.com/gammazero/workerpool#WorkerPool.Pause) function in workerpool.
