### ISSUE TITLE
Start versioning project

### ISSUE THREAD

**Issue by LandonTClipp** [gammazero/workerpool#29]
Thanks for the great project! It's really useful. I have a suggestion, you might want to start versioning this package. This makes it easier to make dependencies more explicit in other go projects, and provides more information regarding changes to the code.

**Comment by gammazero** [comment]
Alright, will do.  It's about time.

**Comment by gammazero** [comment]
Added a few enhancements.

Done: https://github.com/gammazero/workerpool/releases
