### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by DeadNumbers** [gammazero/workerpool#30]
When I use something like this
```Go
package main

import (
	"fmt"
	"time"
	"github.com/gammazero/workerpool"
)

func main() {
	wp := workerpool.New(2)
	z := 0
	for {
		r := z
		wp.Submit(func() {
			fmt.Println("Handling request:", r)
			time.Sleep(time.Second * 3)
		})
		z++
	}
	wp.StopWait()
}
```

![leak](https://user-images.githubusercontent.com/9416005/87041696-2540e100-c1e2-11ea-9fda-e518dd961cb7.gif)

**Comment by DeadNumbers** [comment]
Also, this code works fine
```Go
package main

import (
	"fmt"
	"time"
	"github.com/gammazero/workerpool"
)

func main() {
	wp := workerpool.New(2)
	z := 0
	for i:=0;i<0xdeadbeef;i++{
		r := z
		wp.Submit(func() {
			fmt.Println("Handling request:", r)
			time.Sleep(time.Second * 3)
		})
		z++
	}
	wp.StopWait()
}
```

**Comment by gammazero** [comment]
In the first example, I do not see any exit condition for the loop.  So it will endlessly enqueue functions, much faster than they can be executed, until you run out or memory.  In the second example, the loop has an exit condition. So, the loop will exit after enqueuing a number of functions no greater that the number of iterations.

**Comment by gammazero** [comment]
Closing this as it does not appear to a problem with workerpool, but rather in how workerpool is being used.  The godoc states the following:

| If the number of inbound tasks is too many to even queue for pending processing, then the solution is outside the scope of workerpool ...

I have added a [usage note](https://github.com/gammazero/workerpool/blob/master/README.md#usage-note) to the README to specify this.
