### ISSUE TITLE
New release with `Pause` method

### ISSUE THREAD

**Issue by oze4** [gammazero/workerpool#36]
Are there any plans to publish a release with the new Pause method?

**Comment by gammazero** [comment]
I need to make a couple of modifications first:
- Must be able to stop paused workerpool
- Handle concurrent calls to pause (so the do not deadlock each other)
- Define appropriate pause while paused behavior

I should have all of this finished tonight.

**Comment by oze4** [comment]
@gammazero you are awesome! You don't have to rush anything just because of this issue. Nothing I'm working on is urgent. 

I am fairly new to Go and have been admiring your work over the past week or so (deque is sexy) learning from it.. Let's just say it has been a tremendous help.. I cannot thank you enough!

I went ahead and wrote a little extension for workerpool that allows you to gather results and time each job, [workerpoolxt](https://github.com/oze4/workerpoolxt). I would genuinely love your criticism if you ever have any free time 😄

**Comment by gammazero** [comment]
@oze4 Here is the latest: https://github.com/gammazero/workerpool/releases/tag/v1.1.0
Doc about [Pause](https://godoc.org/github.com/gammazero/workerpool#WorkerPool.Pause)

Thank you for you interest in this project. I think it is awesome that you wrote and extension.  I will take a look at it soon, and maybe have some feedback.
