### ISSUE TITLE
Cannot work with deque 0.2.0

### ISSUE THREAD

**Issue by yulin-li** [gammazero/workerpool#63]
got error

```
../go/pkg/mod/github.com/gammazero/workerpool@v1.1.2/workerpool.go:50:15: cannot use generic type deque.Deque[T any] without instantiation
```

**Comment by shiqi-synctera** [comment]
@yulin-li  so what's really interesting here is that workerpool 1.1.2 itself points to deque 0.1.0

Something in your project is pulling in v0.2.0, which doesn't play well with workerpool 1.1.2. 

If there's nothing that explicitly imports deque 0.2.0 I recommend that you do a `go get github.com/gammazero/deque@v0.1.0` to put it back at 0.1.0, and workerpool will then compile.
