### ISSUE TITLE
Losing tasks?

### ISSUE THREAD

**Issue by keltia** [gammazero/workerpool#7]
Running the example from `README` with go 1.11 on macOS 10.13.6, I see that in many runs, it mostly miss many requests, how so?

```
$ ./foo
Handling request: beta
Handling request: alpha
$ ./foo
Handling request: beta
Handling request: alpha
$ ./foo
Handling request: beta
Handling request: gamma
Handling request: delta
Handling request: epsilon
Handling request: alpha
$ ./foo
Handling request: beta
Handling request: alpha
$ ./foo
Handling request: beta
Handling request: alpha
$ ./foo
Handling request: beta
Handling request: alpha
```

**Comment by gammazero** [comment]
Thank you for noticing that!  Needed to change `wp.Stop()` to `wp.StopWait()` to wait for goroutines to complete before stopping worker pool.

When I wrote the example, I only intended to show how to stop the worker pool, with the assumption that callers would stop however they deemed appropriate with or without waiting.
